spring.application.name=FootyFocusFinal


# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:4321/FootyFocus
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#api urls
leagueStandings.api.url = http://api.football-data.org/v4/competitions/{leagueCode}/standings?season={season}
detailedPlayer.api.url = http://api.football-data.org/v4/persons/
topScorer.api.url=http://api.football-data.org/v4/competitions/{leagueCode}/scorers?season={season}
compWinners.api.url = http://api.football-data.org/v4/competitions/

#api key
football.api.key=${FOOTBALL_DATA_ORG_API_KEY}
